apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app-mf3
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=tanzu-java-web-app-mf3"
#    backstage.io/techdocs-ref: dir:./../.. #this has been used to generate the techdocs for the workload.
  links:
    - url: https://tanzu-java-web-app-mf3.dev-ns-03.tap.dieunkrauts.de/
      title: Tanzu Java Web App
      icon: catalog
spec:
  type: service
  lifecycle: experimental
  owner: default-team
---
#below are the added details for the API portal generation.
apiVersion: backstage.io/v1alpha1
kind: API 
metadata:
  name: demo-api-java-web-app-mf
  description: The demo API for java web app
  links:
    - url: https://tanzu-java-web-app-mf3.dev-ns-03.tap.dieunkrauts.de/swagger-ui/index.html  # could be replaced with the endpoint of our own graphql 
      title: API Definition Java Web App
      icon: docs
spec:
  type: graphql  # Specify the desired API type, e.g., "graphql" or "openapi"
  lifecycle: experimental
  owner: default-team
  system: demo-app-java-web-app # Or specify system name of your choice
  definition: |
    type Query {
      hello: String
    }
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: java-web-app-domain
  description: Demo Domain for Java Web App
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: default-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: java-web-app-demo
  description: Demo Application for angular demo
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: default-team
  domain: demo-domain
