apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: node-express
spec:
  params:
  - name: testing_pipeline_matching_labels # referencing a specific pipeline
    value:
      apps.tanzu.vmware.com/language: nodejs
  source:
    git:
      url: https://github.com/nariman-13/tap
      ref:
        branch: workload-testing
      subpath: node-express
